# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImag'e: 'ubuntu-latest'

jobs:
- job: Job1
  steps:
  - bash: echo  build first Job
  - bash: echo $(build.buildNumber)
  - bash: echo $(build.SourceDirectory)
  - bash: ls -R $(build.SourceDirectory)
  - bash: echo $(build.DefaultworkingDirectory)
  - bash: ls -R $(build.DefaultworkingDirectory)
  - bash: echo $(build.artifactstagingdirectory)
  - bash: ls -R $(build.artifactstagingdirectory)
  - bash: echo $(build.buildNumber)